[project]
name = "funuser"
version = "0.1.3"
description = "User Management System"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [ "click>=8.1.8", "fastapi>=0.141.1", "pymysql>=1.1.1", "sqlalchemy>=2.0.40", "uvicorn>=0.33.0", "python-jose[cryptography]>=3.4.0", "passlib[bcrypt]>=1.7.4", "bcrypt<4.1", "pydantic[email]>=2.4.2",]
[[project.authors]]
name = "niuliangtao"
email = "farfarfun@qq.com"

[project.scripts]
funuser = "funuser.cli:cli"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.setuptools]
license-files = []

[dependency-groups]
dev = [ "pytest>=8.0.0", "httpx>=0.27.0",]
